const demand = (module.exports = {
  house_controller: require("./house-controller"),
  user_controller: require("./user-controller"),
  feedback_controller: require("./feedback-controller"),
  complete_verification: require("./complete-verification-controller"),
  booking_controller: require("./booking-controller"),
  request_controller: require("./request-controller"),
  auth_controller: require("./auth-controller"),
  payment_control: require("./payment-controller"),
  demand_controller: require("./demand-controller"),
  tour_controller: require("./tour-controller"),
  favorite_controller: require("./favorite-controller"),
  payout_controller: require("./payout-controller"),
  analytics_controller: require("./analytics-controller"),
});
